-- 1
SELECT * 
FROM member_tbl_11;
-- 2
SELECT M_NAME, M_BIRTHDAY 
FROM member_tbl_11;
-- 3
SELECT M_ID, M_BIRTHDAY, M_POINT
FROM member_tbl_11
WHERE M_NAME = '박해수';
-- 4
SELECT M_NAME, M_TEL
FROM member_tbl_11
WHERE M_POINT >= 2000;
-- 5
SELECT M_NAME, M_TEL
FROM member_tbl_11
WHERE M_POINT BETWEEN 2000 AND 3000;
-- 6
SELECT M_NAME, M_TEL, M_POINT
FROM member_tbl_11
WHERE M_GRADE = '01';
-- 7
SELECT M_NAME, M_TEL
FROM member_tbl_11
WHERE M_BIRTHDAY > '2004-06-01';
-- 8
SELECT M_NAME, M_BIRTHDAY
FROM member_tbl_11
WHERE M_BIRTHDAY < '2004-05-01';
-- 9
SELECT M_NAME, M_TEL, M_GRADE
FROM member_tbl_11
WHERE M_GRADE <> '01';
-- 10
SELECT M_ID, M_NAME, M_TEL
FROM member_tbl_11
WHERE M_GRADE = '02';
-- 11
SELECT M_NAME, M_TEL
FROM member_tbl_11
WHERE M_POINT < 1500;
-- 12
SELECT *
FROM member_tbl_11
WHERE M_POINT IS NULL;
-- 13
SELECT *
FROM member_tbl_11
WHERE M_POINT IS NOT NULL;
-- 14
SELECT DISTINCT M_GRADE
FROM member_tbl_11;