--1
SELECT M_ID, M_NAME
FROM member_tbl_11
WHERE M_GRADE = '01'
AND M_POINT >= 2000;
--2
SELECT M_ID, M_NAME
FROM member_tbl_11
WHERE M_GRADE = '01'
OR M_POINT >= 2000;
--3
SELECT M_ID, M_NAME, M_GRADE
FROM member_tbl_11
WHERE M_NAME LIKE '김%';
--4
SELECT M_ID, M_NAME, M_GRADE
FROM member_tbl_11
WHERE M_NAME LIKE '%수';
--5
SELECT M_ID, M_NAME, M_GRADE
FROM member_tbl_11
WHERE M_GRADE IN ('01', '03');
--6
SELECT M_ID, M_NAME, M_GRADE
FROM member_tbl_11
WHERE M_GRADE NOT IN ('01', '02');
--7
SELECT M_ID, M_NAME, M_GRADE
FROM member_tbl_11
WHERE M_GRADE = '02'
OR M_NAME LIKE '이%';
--8
SELECT M_ID, M_NAME, M_BIRTHDAY
FROM member_tbl_11
WHERE M_BIRTHDAY < '2004-05-01'
OR M_GRADE = '03';