-- 교재 70페이지
-- 단일행 함수

-- 문자함수
-- INITCAP() 함수
-- 첫글자만 대문자로 변환 나머지는 소문자변환

SELECT * FROM EMP;

SELECT ENAME, INITCAP(ENAME) FROM EMP;

-- LOWER() 함수 : 소문자로 변경
-- UPPER() 함수 : 대문자로 변경

SELECT * FROM EMP;

SELECT ENAME FROM EMP;

SELECT ENAME , LOWER(ENAME), UPPER(ENAME)
FROM EMP;

-- LENGTH : 문자열의 길이를 구하는 함수
SELECT * FROM EMP;
SELECT ENAME, LENGTH(ENAME) as CNT
FROM EMP;

-- || 연결연산자
-- CONCAT() 함수

SELECT * FROM EMP;

SELECT ENAME, JOB
FROM EMP;

SELECT ENAME || ' ' || JOB
FROM EMP;

SELECT CONCAT(ENAME, JOB)
FROM EMP;

-- SUBSTR()
-- 문자열에서 필요한 부분만 추출하여 사용

SELECT SUBSTR('ABCD',2,1) FROM DUAL;
SELECT SUBSTR(ENAME,2,1) FROM EMP;
SELECT SUBSTR(ENAME,-1,1) FROM EMP; -- 오른쪽 한 개

-- INSTR() 함수
-- 문자열내에서 특정문자의 위치 반환

SELECT 'A-B-C-D' FROM DUAL;
SELECT INSTR('A-B-C-D','-') FROM DUAL; -- 첫번째 위치에서 첫번쨰 만나는 지정된 문자의 위치를 반환 / -는 2번째 등장
SELECT INSTR('A-B-C-D','-',1,3) FROM DUAL; -- 3번째 -는 총 6번째 위치에 있음

-- 사용 예1
SELECT
    NAME,
    TEL,
    INSTR(TEL,')')
FROM STUDENT
WHERE DEPTNO1 = 201;
-- 사용 예2
SELECT 
    NAME,
    TEL,
    INSTR(TEL, '3')
FROM STUDENT
WHERE DEPTNO1 = 101;
-- 퀴즈1
SELECT 
    NAME,
    TEL,
    SUBSTR(TEL, 1, INSTR(TEL, ')') - 1) AS "AREA CODE"
FROM STUDENT
WHERE DEPTNO1 = 201;
--- 풀이---
-- TEL에서  ')' 찾기  --INSTR
SELECT TEL FROM STUDENT;

SELECT TEL  , INSTR(TEL,  ')' )  FROM STUDENT;


SELECT TEL FROM STUDENT;
SELECT TEL  , INSTR(TEL,  ')' )  ,  INSTR(TEL,  ')' ) -1
FROM STUDENT;


--
SELECT  NAME, 
       TEL, 
       SUBSTR(TEL ,1,  INSTR(TEL,  ')' ) -1  )
FROM STUDENT;
-------

-- LPAD() 함수 / RPAD()는 오른쪽
-- LPAD(컬럼명, 자리수, 채울문자)
SELECT NAME, ID
FROM STUDENT;

SELECT NAME, ID, LPAD(ID, 20, '*')
FROM STUDENT;

SELECT NAME, ID, RPAD(ID, 20, '*')
FROM STUDENT;

-- 공백제거 또는 특정문자 제거
-- LTRIM
-- RTRIM
-- TRIM

-- 공백 조심
-- A공백
-- A

-- "A " "A" - 가져온데이터가 같은 모습이지만 다르다고 나오면 공백 의심 => 공백 제거

SELECT 'A ' FROM DUAL;
SELECT RTRIM ('A ') FROM DUAL;

SELECT '    A', LTRIM('    A') FROM DUAL;

SELECT ENAME FROM EMP;
-- 오른쪽에서 마지막에 있는 R제거하기
SELECT ENAME, RTRIM(ENAME, 'R')
FROM EMP;

-- REPLACE() 함수
-- REPLACE( 문자열, '문자1','문자2')
SELECT ENAME
FROM EMP;
-- S를 A로
SELECT ENAME, REPLACE(ENAME,'S','A')
FROM EMP;

-- 이름의 첫글자만 별로 바꾸기
SELECT ENAME, REPLACE (ENAME,'S','*')
FROM EMP;
SELECT ENAME, REPLACE (ENAME,'A','*')
FROM EMP;
SELECT ENAME, REPLACE (ENAME,'J','*')
FROM EMP;

-- 찾는문자가 고정될 수 없다
-- => 찾는 문자 구하기
-- 이름에서 첫글자 가져오기
SELECT ENAME, SUBSTR(ENAME,1,1)
FROM EMP;
-- 이후 SUBSTR(ENAME,1,1) 첫글자를 REPLACE 대상으로 주기
SELECT ENAME, REPLACE(ENAME, SUBSTR(ENAME,1,1), '*')
FROM EMP;

-- 문제 풀어보기
-- 사용 예
SELECT NAME, ID, LPAD(ID,10,'*')
FROM STUDENT
WHERE DEPTNO1 = 201;

-- 퀴즈1
SELECT 
    ENAME,
    REPLACE(ENAME, SUBSTR(ENAME, 2, 2), '--') REPLACE
FROM EMP
WHERE DEPTNO = 20;
-- 퀴즈2
--SELECT
--    NAME,
--    JUMIN,
--    REPLACE(
--FROM STUDENT
--WHERE DEPTNO1 = 101;
SELECT 
    NAME,
    REPLACE(JUMIN, SUBSTR(JUMIN, 7), '-///////') REPLACE
FROM STUDENT
WHERE DEPTNO1 = 101;
-- 퀴즈3
SELECT 
    NAME,
    TEL,
    REPLACE(TEL, SUBSTR(TEL, INSTR(TEL, ')') + 1, 3), '***') REPLACE
FROM STUDENT
WHERE DEPTNO1 = 102;
-- 퀴즈4
SELECT 
    NAME,
    TEL,
    REPLACE(TEL, SUBSTR(TEL, INSTR(TEL, '-') + 1), '****') REPLACE
FROM STUDENT
WHERE DEPTNO1 = 101;

-- 다른사람 문제풀이 -----------
SELECT * FROM EMP;

SELECT ENAME, REPLACE(ENAME, 'MI' , '--') 
FROM EMP;

SELECT ENAME,  SUBSTR(ENAME,2,2)
FROM EMP;


SELECT ENAME, REPLACE(ENAME, SUBSTR(ENAME, 2, 2) , '--') 
FROM EMP;

--퀴즈2

-- 84P 퀴즈 2
SELECT NAME, JUMIN, REPLACE(JUMIN, SUBSTR(JUMIN,8,7) , '-/-/-/-') "REPLACE"
FROM STUDENT
WHERE DEPTNO1 = 101;


--퀴즈3
SELECT * FROM STUDENT;
SELECT NAME, TEL,REPLACE(TEL,SUBSTR(TEL,5,3),'***') FROM STUDENT
WHERE DEPTNO1 = 101;


--퀴즈4

SELECT * FROM STUDENT;

SELECT NAME, TEL
FROM STUDENT
WHERE DEPTNO1 = 101;


SELECT NAME, TEL , REPLACE( TEL,  '2158' , '****')
FROM STUDENT;

SELECT NAME, TEL, REPLACE(TEL, SUBSTR(TEL, 9, 4), '****') REPLACE
FROM STUDENT
WHERE DEPTNO1 = 101;


SELECT  INSTR( TEL,  '-')  +1 FROM STUDENT;

SELECT NAME, TEL, REPLACE(TEL, SUBSTR(TEL, INSTR(TEL,'-')+1 , 4), '****') REPLACE
FROM STUDENT
WHERE DEPTNO1 = 101;
------






