-- 교재 70페이지
-- 단일행 함수

-- 문자함수
-- INITCAP() 함수
-- 첫글자만 대문자로 변환 나머지는 소문자변환

SELECT * FROM EMP;

SELECT ENAME, INITCAP(ENAME) FROM EMP;

-- LOWER() 함수 : 소문자로 변경
-- UPPER() 함수 : 대문자로 변경

SELECT * FROM EMP;

SELECT ENAME FROM EMP;

SELECT ENAME , LOWER(ENAME), UPPER(ENAME)
FROM EMP;

-- LENGTH : 문자열의 길이를 구하는 함수
SELECT * FROM EMP;
SELECT ENAME, LENGTH(ENAME) as CNT
FROM EMP;

-- || 연결연산자
-- CONCAT() 함수

SELECT * FROM EMP;

SELECT ENAME, JOB
FROM EMP;

SELECT ENAME || ' ' || JOB
FROM EMP;

SELECT CONCAT(ENAME, JOB)
FROM EMP;

-- SUBSTR()
-- 문자열에서 필요한 부분만 추출하여 사용

SELECT SUBSTR('ABCD',2,1) FROM DUAL;
SELECT SUBSTR(ENAME,2,1) FROM EMP;
SELECT SUBSTR(ENAME,-1,1) FROM EMP; -- 오른쪽 한 개

-- INSTR() 함수
-- 문자열내에서 특정문자의 위치 반환

SELECT 'A-B-C-D' FROM DUAL;
SELECT INSTR('A-B-C-D','-') FROM DUAL; -- 첫번째 위치에서 첫번쨰 만나는 지정된 문자의 위치를 반환 / -는 2번째 등장
SELECT INSTR('A-B-C-D','-',1,3) FROM DUAL; -- 3번째 -는 총 6번째 위치에 있음

-- 사용 예1
SELECT
    NAME,
    TEL,
    INSTR(TEL,')')
FROM STUDENT
WHERE DEPTNO1 = 201;
-- 사용 예2
SELECT 
    NAME,
    TEL,
    INSTR(TEL, '3')
FROM STUDENT
WHERE DEPTNO1 = 101;
-- 퀴즈1
SELECT 
    NAME,
    TEL,
    SUBSTR(TEL, 1, INSTR(TEL, ')') - 1) AS "AREA CODE"
FROM STUDENT
WHERE DEPTNO1 = 201;
--- 풀이---
-- TEL에서  ')' 찾기  --INSTR
SELECT TEL FROM STUDENT;

SELECT TEL  , INSTR(TEL,  ')' )  FROM STUDENT;


SELECT TEL FROM STUDENT;
SELECT TEL  , INSTR(TEL,  ')' )  ,  INSTR(TEL,  ')' ) -1
FROM STUDENT;


--
SELECT  NAME, 
       TEL, 
       SUBSTR(TEL ,1,  INSTR(TEL,  ')' ) -1  )
FROM STUDENT;
-------

-- LPAD() 함수 / RPAD()는 오른쪽
-- LPAD(컬럼명, 자리수, 채울문자)
SELECT NAME, ID
FROM STUDENT;

SELECT NAME, ID, LPAD(ID, 20, '*')
FROM STUDENT;

SELECT NAME, ID, RPAD(ID, 20, '*')
FROM STUDENT;

-- 공백제거 또는 특정문자 제거
-- LTRIM
-- RTRIM
-- TRIM

-- 공백 조심
-- A공백
-- A

-- "A " "A" - 가져온데이터가 같은 모습이지만 다르다고 나오면 공백 의심 => 공백 제거

SELECT 'A ' FROM DUAL;
SELECT RTRIM ('A ') FROM DUAL;

SELECT '    A', LTRIM('    A') FROM DUAL;

SELECT ENAME FROM EMP;
-- 오른쪽에서 마지막에 있는 R제거하기
SELECT ENAME, RTRIM(ENAME, 'R')
FROM EMP;

-- REPLACE() 함수
-- REPLACE( 문자열, '문자1','문자2')
SELECT ENAME
FROM EMP;
-- S를 A로
SELECT ENAME, REPLACE(ENAME,'S','A')
FROM EMP;

-- 이름의 첫글자만 별로 바꾸기
SELECT ENAME, REPLACE (ENAME,'S','*')
FROM EMP;
SELECT ENAME, REPLACE (ENAME,'A','*')
FROM EMP;
SELECT ENAME, REPLACE (ENAME,'J','*')
FROM EMP;

-- 찾는문자가 고정될 수 없다
-- => 찾는 문자 구하기
-- 이름에서 첫글자 가져오기
SELECT ENAME, SUBSTR(ENAME,1,1)
FROM EMP;
-- 이후 SUBSTR(ENAME,1,1) 첫글자를 REPLACE 대상으로 주기
SELECT ENAME, REPLACE(ENAME, SUBSTR(ENAME,1,1), '*')
FROM EMP;

-- 문제 풀어보기
-- 사용 예
SELECT NAME, ID, LPAD(ID,10,'*')
FROM STUDENT
WHERE DEPTNO1 = 201;

-- 퀴즈1
SELECT 
    ENAME,
    REPLACE(ENAME, SUBSTR(ENAME, 2, 2), '--') REPLACE
FROM EMP
WHERE DEPTNO = 20;
-- 퀴즈2
--SELECT
--    NAME,
--    JUMIN,
--    REPLACE(
--FROM STUDENT
--WHERE DEPTNO1 = 101;
SELECT 
    NAME,
    REPLACE(JUMIN, SUBSTR(JUMIN, 7), '-///////') REPLACE
FROM STUDENT
WHERE DEPTNO1 = 101;
-- 퀴즈3
SELECT 
    NAME,
    TEL,
    REPLACE(TEL, SUBSTR(TEL, INSTR(TEL, ')') + 1, 3), '***') REPLACE
FROM STUDENT
WHERE DEPTNO1 = 102;
-- 퀴즈4
SELECT 
    NAME,
    TEL,
    REPLACE(TEL, SUBSTR(TEL, INSTR(TEL, '-') + 1), '****') REPLACE
FROM STUDENT
WHERE DEPTNO1 = 101;

-- 다른사람 문제풀이 -----------
SELECT * FROM EMP;

SELECT ENAME, REPLACE(ENAME, 'MI' , '--') 
FROM EMP;

SELECT ENAME,  SUBSTR(ENAME,2,2)
FROM EMP;


SELECT ENAME, REPLACE(ENAME, SUBSTR(ENAME, 2, 2) , '--') 
FROM EMP;

--퀴즈2

-- 84P 퀴즈 2
SELECT NAME, JUMIN, REPLACE(JUMIN, SUBSTR(JUMIN,8,7) , '-/-/-/-') "REPLACE"
FROM STUDENT
WHERE DEPTNO1 = 101;


--퀴즈3
SELECT * FROM STUDENT;
SELECT NAME, TEL,REPLACE(TEL,SUBSTR(TEL,5,3),'***') FROM STUDENT
WHERE DEPTNO1 = 101;


--퀴즈4

SELECT * FROM STUDENT;

SELECT NAME, TEL
FROM STUDENT
WHERE DEPTNO1 = 101;


SELECT NAME, TEL , REPLACE( TEL,  '2158' , '****')
FROM STUDENT;

SELECT NAME, TEL, REPLACE(TEL, SUBSTR(TEL, 9, 4), '****') REPLACE
FROM STUDENT
WHERE DEPTNO1 = 101;


SELECT  INSTR( TEL,  '-')  +1 FROM STUDENT;

SELECT NAME, TEL, REPLACE(TEL, SUBSTR(TEL, INSTR(TEL,'-')+1 , 4), '****') REPLACE
FROM STUDENT
WHERE DEPTNO1 = 101;
------

--숫자관련함수
--ROUND(컬럼, 출력을 원하는 자리수)
 
--출력을 원하는 자리수 :  -2 -1  0  1  2

SELECT ROUND( 1234.5678, 0) FROM DUAL;
SELECT ROUND( 1234.5678, -1) FROM DUAL;

--TRUNC :버림

SELECT TRUNC( 1234.5678, 0) FROM DUAL;
SELECT TRUNC( 1234.5678, -1) FROM DUAL;


--MOD :나머지
SELECT MOD(11,3) FROM  DUAL;

--CEIL  : 주어진 숫자에서 가까운 큰 정수   3.56  ->  4
--FLOOR : 주어진 숫자에서 가까운 작은 정수   3.56  ->  3
--                                      -3.46   ->  큰,  -3     작은거 -4


SELECT FLOOR( 3.56) FROM DUAL;   -- 3
SELECT CEIL( 3.56) FROM DUAL;   -- 4

SELECT FLOOR( -3.56) FROM DUAL;       -- -4
SELECT CEIL( -3.56) FROM DUAL;        -- -3


--날짜관련 함수  (89페이지)

--현재날짜구하기
SELECT SYSDATE FROM DUAL;

-- 날짜  - 날짜   = 수  (일 수)
-- 날짜 +3 ->  이후 날짜
-- 날짜 -3 =>  이전 날짜

--MONTHS_BETWEEN (큰날짜, 작은날짜)
SELECT  MONTHS_BETWEEN( SYSDATE , '2026-01-22') FROM DUAL ;


--LAST_DAY() 함수
--정해진 날짜가 포함된 달의 마지막 날 구하기
SELECT  SYSDATE  FROM  DUAL;
SELECT  LAST_DAY(SYSDATE)  FROM  DUAL;

--NEXT_DAY()
SELECT SYSDATE  , NEXT_DAY( SYSDATE, '월') FROM DUAL;

--날짜 , 년 ,월, 일 가져오기 

SELECT  SYSDATE FROM DUAL;

SELECT  
    SYSDATE,
    EXTRACT( YEAR FROM SYSDATE) ,
     EXTRACT( MONTH FROM SYSDATE) ,
      EXTRACT( DAY FROM SYSDATE)     
FROM DUAL;


--형변환
--문자 :   VARCHAR2  , CHAR
--숫자  :  NUMBER 
--날짜  : DATE
--1)형변환  - 표시형식 
-- 숫자  ->  문자  (천단위, 통화단위)
-- 날짜  ->  문자  (원하는 표시형식으로 지정하고 싶을 때)

--2) 숫자연산을 위해서
-- 문자  ->  숫자

--3) 날짜데이터로 다루기 위해서 
-- 문자  ->  날짜 

--형변환함수
--명시적형변환 , 묵시적형변환(자동형변환)
SELECT  2+'2' FROM DUAL;  --  2+ '2' -> 문자  2가 자동으로 숫자로 변환되었음  (자동형변환)
--
SELECT 2 + TO_NUMBER('2') FROM DUAL;

--TO_CHAR()  : 숫자, 날짜를 문자로 형변환 하는 것
SELECT  SYSDATE  FROM DUAL;
SELECT  TO_CHAR(SYSDATE ,  'YYYY-MM-DD' )  FROM DUAL;
SELECT  TO_CHAR(SYSDATE , 'YYYY/MM/DD')  FROM DUAL;
SELECT  TO_CHAR(SYSDATE , 'YYYY')  FROM DUAL;
SELECT  TO_CHAR(SYSDATE , 'MM')  FROM DUAL;
SELECT  TO_CHAR(SYSDATE , 'DD')  FROM DUAL;
SELECT  TO_CHAR(SYSDATE , 'DAY')  FROM DUAL;
SELECT  TO_CHAR(SYSDATE , 'DY')  FROM DUAL;

-- 시분초

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD : HH24:MI:SS') FROM DUAL;

-- 숫자를 문자로

SELECT * FROM ACORNTBL;

SELECT NAME, TO_CHAR(POINT, '999,999') FROM ACORNTBL; -- 의미 없는 0은 표시 xx
SELECT NAME, TO_CHAR(POINT, 'L999,999') FROM ACORNTBL;
SELECT NAME, TO_CHAR(POINT, '$999,999') FROM ACORNTBL;
SELECT NAME, TO_CHAR(POINT, '$099,999') FROM ACORNTBL;

-- 형변환 주의사항
-- 문자 > 문자변환 불가
-- 숫자 > 숫자변환 불가

-- TO_NUMBER()
-- TO_CHAR()
-- TO_DATE() : 날짜 형식을 갖춘 문자 > 날짜데이터로 바꾸기
SELECT TO_DATE('2000-01-01') FROM DUAL;


-- 107p
-- 사용예1

-- 사용예2

-- 퀴즈1






